server:
  port: 9876

spring:
  servlet:
    multipart:
      max-file-size: 20MB #单个文件最大为20M
      max-request-size: 20MB #单次请求文件总数大小为20M

  datasource:
    username: root
    password: root@@@###
    url: jdbc:mysql://qin.qins.online/petShop?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  mvc:
    view:
      static-path-pattern: /static/**

mybatis:
  mapper-locations: classpath:mapper/*.xml

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#文件保存路径
files:
  upload:
    path: D:/petShopCode/files/


